### ISSUE TITLE
Mis-aligned context menu icons after installing the theme on Firefox 91

### ISSUE THREAD

**Issue by ADTC** [black7375/Firefox-UI-Fix#161]
**Describe the bug**
I've installed the theme on Firefox 91 since they removed the official support to turn off the hideous Proton UI. Things look great, except the context menu icons are overlaid on the text.

The spacing between the icon and the text in the Hamburger menu also doesn't appear to be proper (though they don't overlap).

**Expected behavior**
Icons are properly aligned with correct spacing.

**Screenshots**
Context Menus:
![image](https://user-images.githubusercontent.com/6047296/129365661-8356d85c-bd88-4ba3-95f9-2cdd0a37ec97.png)
Burger Menu:
![image](https://user-images.githubusercontent.com/6047296/129365899-b187cbbb-e91a-4554-a867-75ad1717e345.png)

**Environment (please complete the following information):**
 - Distribution: [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
 - Firefox Version: 91.0
 - OS: Windows 10
 - Theme: Light

**Additional context**
Problem appears similar to issue #158

**Comment by black7375** [comment]
What is your Windows version?
I know there's a problem with 8 right now and I'm setting up the environment to fix it over the weekend!!

**Comment by ADTC** [comment]
@black7375 
Edition	Windows 10 Home Single Language
Version	20H2
Installed on	‎7/‎17/‎2020
OS build	19042.985
Experience	Windows Feature Experience Pack 120.2212.2020.0

**Comment by Hapax96** [comment]
I was just about to post the same problem. I also just (installed) the theme after updating to Firefox 91 and the changes via about:config no longer had any effect. I have Windows 8.1.

![dllhost_QNXUsCWGEX](https://user-images.githubusercontent.com/88907420/129413670-63989348-671f-49cb-99b7-555d0bfd38bf.png)
![firefox_E3NMRYXIuB](https://user-images.githubusercontent.com/88907420/129413673-1766073a-06a9-4702-998b-3c2cab2dcd77.png)

**Comment by black7375** [comment]
![image](https://user-images.githubusercontent.com/25581533/129477400-2dd67888-e9f8-4f37-a3a0-479a82d89a70.png)
Hmm... this is weird. It is difficult to reproduce.
Did you use any other custom code or `about:config` setting?

---

win7 and win8 have been fixed. #145

**Comment by Hapax96** [comment]
I only disabled Proton via about:config when that was still possible. I only noticed later that you seem to offer different versions here. I use the Photon style. There the problem has not been fixed yet, I think? If I use the green download button instead, the icons are displayed normally. Then I also see all the icons in the settings, which is not the case with Proton, right? At least I don't see all of them.

**Comment by black7375** [comment]
Yes. It will be corrected in the future. https://github.com/black7375/Firefox-UI-Fix/issues/149#issuecomment-899011060

**Comment by ADTC** [comment]
Let me find some time to test with a clean install. Thanks.

**Comment by black7375** [comment]
Have you ever tried it?

**Comment by ADTC** [comment]
@black7375 I changed the code to v4.0.0. Unfortunately, the issue still exists. I'll do more testing and let you know soon.

**Comment by black7375** [comment]
Thanks for testing.
I tested it with two devices, but it is not easy because it is not reproduced.

**Comment by ADTC** [comment]
### I'm sorry.
This was entirely my fault! I tried to integrate my existing `userChrome.css` with Lepton. By elimination, I found that the following namespace declaration (in my existing customization) was the root cause of the problem:
```
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");
```

I was able to keep the rest of my customization except the above line, and everything works perfectly now (both Lepton and my customization). I've no idea why that namespace was there, or why it would ever be necessary. **Well, nuked it and problem solved.**

**PS:** I also removed the other namespace declaration though it wasn't causing any problems. Not sure what this is for either:
```
@namespace html url("http://www.w3.org/1999/xhtml");
```

**Comment by black7375** [comment]
If you want to put an `namespace`, you'll have to do this.
I was also testing recently.
```css
@namespace xul url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");
@namespace html url("http://www.w3.org/1999/xhtml");
```

**Comment by ADTC** [comment]
Thanks for the tip. I'm going to leave it out for now as things seem to be working fine.

BTW: The _"Inspect"_ option seems to have lost its icon in Firefox 92.
![image](https://user-images.githubusercontent.com/6047296/132864698-0dad8bd0-9320-4665-acd9-274ad44a7598.png)

**Comment by black7375** [comment]
It have been fixed in A https://github.com/black7375/Firefox-UI-Fix/commit/74bd1ca1322adb6731a52101fd7dcc1fc4746573

**Comment by neilpat05** [comment]
<img width="277" alt="image" src="https://github.com/user-attachments/assets/644f06e5-dc1f-4b14-b1a3-d387390a5177">

This is how it looks like on MacOS v131.0.3 (aarch64)
