### ISSUE TITLE
right click menu icons and text broken

### ISSUE THREAD

**Issue by kolva3** [black7375/Firefox-UI-Fix#331]
**Describe the bug**
The logos are broken. I attempted to update with powershell before this issue, but to no fix.

**Expected behavior**
For the icons and text to be spaced out.

**Screenshots**
 ![Capture](https://user-images.githubusercontent.com/83851584/153665277-151206d3-eeab-41f3-9278-58655b071d2f.PNG)

**Environment:**

 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [ ] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [ ] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
 - Firefox Version: 
 - OS:
   - [ ] Linux
   - [x] Windows
   - [ ] Mac
   - [ ] Other: 
 - Theme:
   - [ ] Light
   - [x] Dark
   - [ ] Alpenglow (System: Light)
   - [ ] Alpenglow (System: Dark)
   - [ ] System Default
     - GTK Theme Name (Linux only): 
   - [ ] Other: (e.g. [Photon Colors](https://addons.mozilla.org/en-US/firefox/addon/photon-colors/), [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/), [Fairytale Of Nature](https://addons.mozilla.org/en-US/firefox/addon/fairytale-of-nature/))

**Additional context**
Firefox Nightly updated before I see this error

**Comment by kolva3** [comment]
also happens on bookmarks 
![Capture](https://user-images.githubusercontent.com/83851584/153693301-a5d47b8a-c5cb-45d6-9059-9d0c14fba4ca.PNG)

**Comment by black7375** [comment]
Because of this commit https://github.com/mozilla/gecko-dev/commit/5fed8de04b3de8bb7a213deb37150af18d0b3314

It will be changed as follows:
```css
@media (-moz-os-version: windows-win10) {
}
```

to

```css
/* v99 */
@media (-moz-platform: windows-win10) {
}
```

It also has a media query for Mac and Linux. https://github.com/mozilla/gecko-dev/commit/5fed8de04b3de8bb7a213deb37150af18d0b3314#diff-314c90db7a8ea5667e97a1ff5079d02192246d424244fc9dcebd568f3e1c87e7
```css
@media (-moz-platform: linux), (-moz-platform: macos)  {
}
```

**Comment by black7375** [comment]
I updated the code. Please do the test.

**Comment by maicol07** [comment]
@black7375 can you add that to the proton style?

**Comment by black7375** [comment]
@maicol07 yep, updated :+1:

**Comment by Ryunam** [comment]
Unfortunately I'm still experiencing this issue too on my system. Since the powershell script wasn't working, I manually updated the Leoton UI a few seconds ago by copying the relevant files in my profile directory, all in the hopes of addressing this problem.However, my icons are still overlapping with the corresponding text strings. 

This is with Firefox version 100.0.2, with the "Original Lepton" style. See here for further reference:

![image](https://user-images.githubusercontent.com/17614150/170863368-559b228a-264a-4309-bbbe-acfe1dcefed9.png) 

![image](https://user-images.githubusercontent.com/17614150/170863384-ab2338d9-284f-4aa8-8433-4bb997c5a252.png)
