### ISSUE TITLE
Improve spacing between address bar and tab bar

### ISSUE THREAD

**Issue by connie-e** [black7375/Firefox-UI-Fix#662]
### Is your feature request related to a problem?

I don't like the address bar being so close to the tab bar. In previous Firefox designs there was better spacing between these two elements.

### The solution I'd like

I'd prefer for some extra spacing between these two elements. Preferably I'd like the user to be able to specify how much spacing they want too.

### Screenshots or video

![image](https://user-images.githubusercontent.com/43714528/224467133-664536e6-438c-4f1d-9bd6-0002787c5435.png)
**Added Spacing**

![image](https://user-images.githubusercontent.com/43714528/224467146-74a4fdbb-c8b1-446e-b604-4f42212aa734.png)
**Current Spacing**

### Alternatives I've considered

I've tried to edit the CSS file myself but absolutely no luck in that.  ¯\_(ツ)_/¯

### Additional context

I've found no other issues bringing this up.

**Comment by didacta** [comment]
This seems to have been addressed 
<img width="106" alt="image" src="https://github.com/black7375/Firefox-UI-Fix/assets/9103032/69f11885-8a16-4848-b8f9-b019a7c846bb">

**Comment by connie-e** [comment]
> This seems to have been addressed <img alt="image" width="106" src="https://user-images.githubusercontent.com/9103032/256688069-69f11885-8a16-4848-b8f9-b019a7c846bb.png">

I've tested every style option and this has not been fixed.

**Comment by didacta** [comment]
> > This seems to have been addressed <img alt="image" width="106" src="https://user-images.githubusercontent.com/9103032/256688069-69f11885-8a16-4848-b8f9-b019a7c846bb.png">
> 
> 
> 
> I've tested every style option and this has not been fixed.

would you be able to provide a screenshot with the style option it is not working for? I can look into this

**Comment by connie-e** [comment]
> > > This seems to have been addressed <img alt="image" width="106" src="https://user-images.githubusercontent.com/9103032/256688069-69f11885-8a16-4848-b8f9-b019a7c846bb.png">
> > 
> > 
> > I've tested every style option and this has not been fixed.
> 
> would you be able to provide a screenshot with the style option it is not working for? I can look into this

I've provided the examples of all three along with vanilla Firefox. The Lepton themes still have the small spacing as the one in the original post I made.

![image](https://github.com/black7375/Firefox-UI-Fix/assets/43714528/6bf84fc2-38d7-45ed-b114-a05886f565b5)
Vanilla Firefox

![image](https://github.com/black7375/Firefox-UI-Fix/assets/43714528/f0b5cd3d-096a-4520-a843-af048aada832)
Lepton

![image](https://github.com/black7375/Firefox-UI-Fix/assets/43714528/87a7fd3d-0288-44c3-b4b6-cae7e07b6d5a)
Lepton Proton

![image](https://github.com/black7375/Firefox-UI-Fix/assets/43714528/7b4ffc4d-3bff-4b82-9f61-5993bf3578b8)
Lepton Photon

**Comment by black7375** [comment]
Hello, how about using this code?

```css
#nav-bar {
  padding-block: 2px !important;
}
```

**Comment by connie-e** [comment]
> Hello, how about using this code?
> 
> ```css
> #nav-bar {
>   padding-block: 2px !important;
> }
> ```

![image](https://github.com/black7375/Firefox-UI-Fix/assets/43714528/1cab8692-e915-4d98-92ad-f8ba0b240ad9)
This sort of works but does end up making the bottom of the URL area too small.

**Comment by black7375** [comment]
Now, this issue applied with [`v8.5.0`](https://github.com/black7375/Firefox-UI-Fix/releases/tag/v8.5.0).
I tried to make it as balanced as possible.

Thank you for your patience.
Let us know if there's anything I can do better.

**Comment by connie-e** [comment]
Thank you! I'll have to check this out when I get the chance.
